# site settings
title: Moondrop
subtitle: by Nico
email: audeonico443@gmail.com
description: Brand ambassador, video editor, and graphic designer
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: 
state: 
zip_code: 
country: 
phone:

# homepage tiles
tiles-source: custom # accepts "posts" or "pages" or "custom"
custom-pages:
  -
    title: Videos
    url: videos
    image: assets/images/videos/mindsweweave.png
    description: Featuring trailers, documentaries and more
  -
    title: Image Editing and Graphic Editing
    url: graphics
    image: /assets/images/games/djusachi/DJBunnyTitleScreenCentered.png
    description: Featuring graphic design goodness
  -
    title: Games
    url: games
    image: /assets/images/games/djusachi/DJBunnyTitleScreenCentered.png
    description: Featuring game projects

tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/nicholas-marinello-331884224/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
