# site settings
title: Moondrop
subtitle: by Nico
email: audeonico443@gmail.com
description: Video editor, graphic designer and brand ambassador
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: 
state: 
zip_code: 
country: 
phone:

# homepage tiles
tiles-source: custom # accepts "posts" or "pages" or "custom"
custom-pages:
  -
    title: Videos
    url: videos
    image: assets/images/puyonthumbnail.png
    description: Featuring trailers, documentaries and more!
  -
    title: Games
    url: games
    image: /assets/images/DJ_Usachi.png
    description: Featuring Games
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/nicholas-marinello-331884224/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
